[package]
name = "green-threads"
version = "0.1.0"
authors = ["Ziyi Yan <ziyi.yan@foxmail.com>"]
edition = "2018"

[dependencies]
num_cpus = "1.13.0"
rayon = "1.3.1"

# needed until https://github.com/rust-lang/rust/pull/74105
[profile.dev]
opt-level = 1
